'use client'

import { useState } from 'react'
import {
  AlertCircle,
  Loader2,
  ExternalLink,
  CheckCircle2,
} from 'lucide-react'
import { github, ImpactAnalysis, CodebaseImpact } from '@/lib/api'
import toast from 'react-hot-toast'

interface CreateIssueButtonProps {
  owner: string
  repo: string
  impactData?: ImpactAnalysis | null
  codebaseData?: CodebaseImpact | null
  mode: 'file' | 'codebase'
}

function buildIssueBody(
  mode: 'file' | 'codebase',
  impact?: ImpactAnalysis | null,
  codebase?: CodebaseImpact | null
): { title: string; body: string; labels: string[] } {
  if (mode === 'file' && impact) {
    const riskEmoji =
      impact.risk_level === 'high' ? '🔴' : impact.risk_level === 'medium' ? '🟡' : '🟢'

    let body = `## ${riskEmoji} Impact Analysis Report\n\n`
    body += `**File:** \`${impact.target_file}\`\n`
    if (impact.symbol) body += `**Symbol:** \`${impact.symbol}\`\n`
    body += `**Risk Score:** ${impact.risk_score}/100 (${impact.risk_level})\n\n`

    body += `### Affected Files (${impact.total_affected})\n\n`
    for (const f of impact.affected_files.slice(0, 20)) {
      body += `- \`${f}\`\n`
    }
    if (impact.affected_files.length > 20) {
      body += `- _...and ${impact.affected_files.length - 20} more_\n`
    }

    if (impact.circular_dependencies.length > 0) {
      body += `\n### ⚠️ Circular Dependencies\n\n`
      for (const cycle of impact.circular_dependencies) {
        body += `- ${cycle.join(' → ')} → ${cycle[0]}\n`
      }
    }

    if (impact.recommended_refactor_steps.length > 0) {
      body += `\n### Recommended Fix\n\n`
      impact.recommended_refactor_steps.forEach((step, i) => {
        body += `${i + 1}. ${step}\n`
      })
    }

    body += `\n---\n*Generated by DocuVerse Impact Analysis*`

    return {
      title: `[Impact] ${impact.risk_level.toUpperCase()} risk: ${impact.target_file}`,
      body,
      labels: ['docuverse', `risk:${impact.risk_level}`],
    }
  }

  if (mode === 'codebase' && codebase) {
    const riskEmoji =
      codebase.overall_risk_level === 'high'
        ? '🔴'
        : codebase.overall_risk_level === 'medium'
        ? '🟡'
        : '🟢'

    let body = `## ${riskEmoji} Codebase Impact Report\n\n`
    body += `**Overall Risk:** ${codebase.overall_risk_score}/100 (${codebase.overall_risk_level})\n`
    body += `**Files:** ${codebase.total_files} | **Dependencies:** ${codebase.total_dependencies}\n`
    body += `**Is DAG:** ${codebase.is_dag ? 'Yes ✅' : 'No ❌'}\n\n`

    if (codebase.hotspots.length > 0) {
      body += `### 🔥 Hotspot Files\n\n`
      body += `| File | Risk | Dependents | Affected |\n|---|---|---|---|\n`
      for (const hs of codebase.hotspots.slice(0, 10)) {
        body += `| \`${hs.file}\` | ${hs.risk_score} (${hs.risk_level}) | ${hs.direct_dependents} | ${hs.total_affected} |\n`
      }
    }

    if (codebase.circular_dependencies.length > 0) {
      body += `\n### ⚠️ Circular Dependencies (${codebase.circular_dependencies.length})\n\n`
      for (const cycle of codebase.circular_dependencies.slice(0, 10)) {
        body += `- ${cycle.join(' → ')} → ${cycle[0]}\n`
      }
    }

    if (codebase.recommended_actions.length > 0) {
      body += `\n### Recommended Actions\n\n`
      codebase.recommended_actions.forEach((action, i) => {
        body += `${i + 1}. ${action}\n`
      })
    }

    body += `\n---\n*Generated by DocuVerse Impact Analysis*`

    return {
      title: `[Codebase Impact] ${codebase.overall_risk_level.toUpperCase()} risk — ${codebase.total_files} files analyzed`,
      body,
      labels: ['docuverse', `risk:${codebase.overall_risk_level}`],
    }
  }

  return { title: '', body: '', labels: [] }
}

export function CreateIssueButton({
  owner,
  repo,
  impactData,
  codebaseData,
  mode,
}: CreateIssueButtonProps) {
  const [isCreating, setIsCreating] = useState(false)
  const [issueUrl, setIssueUrl] = useState<string | null>(null)

  const handleCreate = async () => {
    const { title, body, labels } = buildIssueBody(mode, impactData, codebaseData)
    if (!title) return

    setIsCreating(true)
    try {
      const result = await github.createIssue(owner, repo, title, body, labels)
      setIssueUrl(result.url)
      toast.success(`Issue #${result.issue_number} created!`)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to create issue'
      toast.error(message)
    } finally {
      setIsCreating(false)
    }
  }

  const hasData = mode === 'file' ? !!impactData : !!codebaseData

  if (issueUrl) {
    return (
      <a
        href={issueUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-semibold rounded-lg bg-dv-success/10 text-dv-success hover:bg-dv-success/15 transition-all"
      >
        <CheckCircle2 className="w-3 h-3" />
        View Issue
        <ExternalLink className="w-3 h-3" />
      </a>
    )
  }

  return (
    <button
      onClick={handleCreate}
      disabled={isCreating || !hasData}
      className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-semibold rounded-lg bg-dv-accent/10 text-dv-accent hover:bg-dv-accent/15 transition-all disabled:opacity-40 disabled:pointer-events-none active:scale-[0.95]"
    >
      {isCreating ? (
        <Loader2 className="w-3 h-3 animate-spin" />
      ) : (
        <AlertCircle className="w-3 h-3" />
      )}
      {isCreating ? 'Creating…' : 'Create Issue'}
    </button>
  )
}
