'use client'

import { useState } from 'react'
import { Upload, Loader2, CheckCircle2, ExternalLink, AlertCircle } from 'lucide-react'
import { github, documentation, RepositoryDocumentation } from '@/lib/api'
import toast from 'react-hot-toast'

interface PushDocsButtonProps {
  repoId: string
  fullName: string          // "owner/repo"
  docs: RepositoryDocumentation | null
}

export function PushDocsButton({ repoId, fullName, docs }: PushDocsButtonProps) {
  const [isPushing, setIsPushing] = useState(false)
  const [resultUrl, setResultUrl] = useState<string | null>(null)

  const handlePush = async () => {
    if (!docs) {
      toast.error('Generate documentation first')
      return
    }

    const [owner, repo] = fullName.split('/')
    if (!owner || !repo) {
      toast.error('Invalid repository name')
      return
    }

    setIsPushing(true)
    setResultUrl(null)
    try {
      // Format as markdown
      let md = `# ${fullName} — Documentation\n\n`
      md += `> Auto-generated by [DocuVerse](https://docuverse.ai)\n\n`
      md += `## Overview\n\n${docs.overview}\n\n`
      md += `## Architecture\n\n${docs.architecture}\n\n`
      md += `## Folder Structure\n\n\`\`\`\n${docs.folder_tree}\n\`\`\`\n\n`
      md += `## Dependencies\n\n${docs.dependencies}\n\n`
      md += `## File Documentation\n\n`
      for (const f of docs.files) {
        md += `### ${f.path}\n\n`
        for (const s of f.sections) {
          md += `#### ${s.title}\n\n${s.content}\n\n`
        }
      }

      const result = await github.pushReadme(owner, repo, md)
      setResultUrl(result.url)
      toast.success('README.md pushed to GitHub!')
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to push README'
      toast.error(message)
    } finally {
      setIsPushing(false)
    }
  }

  if (resultUrl) {
    return (
      <a
        href={resultUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="flex items-center gap-2 ios-caption2 font-medium px-3 py-1.5 rounded-[8px] bg-dv-success/10 text-dv-success hover:bg-dv-success/15 transition-colors"
      >
        <CheckCircle2 className="w-3.5 h-3.5" />
        View on GitHub
        <ExternalLink className="w-3 h-3" />
      </a>
    )
  }

  return (
    <button
      onClick={handlePush}
      disabled={isPushing || !docs}
      className="flex items-center gap-2 ios-caption2 font-medium px-3 py-1.5 rounded-[8px] bg-[var(--glass-6)] text-dv-text-muted hover:bg-[var(--glass-8)] transition-colors active:scale-[0.95] disabled:opacity-40 disabled:pointer-events-none"
    >
      {isPushing ? (
        <Loader2 className="w-3.5 h-3.5 animate-spin" />
      ) : (
        <Upload className="w-3.5 h-3.5" />
      )}
      {isPushing ? 'Pushing…' : 'Push to GitHub'}
    </button>
  )
}
